http_server:
  address: "0.0.0.0:8080"
  timeout: 5s
  idle_timeout: 60s
database:
  host: postgres
  port: 5432
  name: cloud_storage
redis:
  host: redis
  port: 6379
session:
  expires_in: 336h # 14 days