http_server:
  address: "0.0.0.0:8080"
  read_timeout: 20m
  write_timeout: 20m
  idle_timeout: 60s

database:
  host: postgres
  port: 5432

redis:
  host: redis
  port: 6379

minio:
  host: minio
  port: 9000

session:
  expires_in: 336h # 14 days